### ISSUE TITLE
Any idea for scroll to group by index

### ISSUE THREAD

**Issue by gioxoay** [GONZALEZD/cupertino_listview#1]
Thank for good widget, but I have question about scroll to group by index?

**Comment by GONZALEZD** [comment]
Hi Gioxoay,
If you want to scroll to group by index, I've made an article about it: https://medium.com/flutter-community/flutter-ios-styled-listview-cc21d8574dd5

In that article, you will understand how to do it, and at the end you will have access to the source code.
If you have more specific questions, feel free to ask!
