### ISSUE TITLE
Is it possible to align the category items in a horizontal listview?

### ISSUE THREAD

**Issue by clarkwillis** [GONZALEZD/cupertino_listview#3]
Is it possible to align the category items also in a horizontal listview on top of the view similar like described in this article.

https://medium.com/flutter-community/create-shop-list-with-flutter-d13d3c20d68b

This would increase the usability of the already great plugin even more.

Thank you for the package!

**Comment by GONZALEZD** [comment]
Hi Clarkwillis,

When i developped that library, I wanted the developers to avoid bad ui
design with an horizontal list (because of the available space in
portrait).

If you can bring me a good usecase (app in  appstore or playstore, or a
video, or ios xcproj) , i will think about adding that feature to Cupertino
listview.

Regards,
David GONZALEZ


Le mer. 17 févr. 2021 à 17:58, clarkwillis <notifications@github.com> a
écrit :

**Comment by clarkwillis** [comment]
Hi David,
thank you for your fast response. 
Yes I can imagine a food app. I also linked a video within that comment.
I can also imagine that your demo is even more easy to navigate with that feature.
![ezgif-4-514c8e0c772c](https://user-images.githubusercontent.com/78764880/108359479-56f63d80-71f0-11eb-9a4f-0fff614b3b1f.gif)

**Comment by razfazz** [comment]
I am interested in this feature as well. I know it from deliveroo

**Comment by GONZALEZD** [comment]
I think we are not talking about the same widget. The Cupertino listview is not a highlevel widget as what you described. Their goals are differents.

Compared to the ListView widget, the cupertino_listview add an extra element floating on top, and representing the current section shown by the list.

In your case, the widget you want has an horizontal listview containing "sections shortcuts".
This is a combination of two widgets: an horizontal and a vertical Listview, both linked by scroll controllers listening to each other.
And added to that, to jump to a specific element of the vertical listview (https://pub.dev/packages/scroll_to_index).


Therefore, these widgets are technically too different. I won't implements it, but you give me a good idea for a medium article :D .

Regards,
David.

**Comment by razfazz** [comment]
looking forward to this article ;)
