### ISSUE TITLE
If `itemInSectionCount` is zero, header for that section does not display

### ISSUE THREAD

**Issue by LEMUSADR000** [GONZALEZD/cupertino_listview#4]
It seems as if this edge case isn't handled in the way that I expected. When you have 0 items in a section, that section does not display. Is this a bug or expected behavior? If expected, is there any way to display a header even when there are no items in that section?  
  
As an aside, great job on this package! I implemented my own version of this but I used slivers and those didn't seem to be as performative as if I had used a ListView, so this saved me quite a bit of time.

**Comment by GONZALEZD** [comment]
Hi, it was an expected behaviour, but idea is interesting so i will add this behaviour (by default)
