### ISSUE TITLE
flutter 3.0 Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by aipame** [GONZALEZD/cupertino_listview#7]
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/src/cupertino_listview_widget.dart:188
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Document/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance!.addPostFrameCallback(_refreshFirstTime);

**Comment by GONZALEZD** [comment]
Fixed
