### ISSUE TITLE
required SectionBuilder floatingSectionBuilder?

### ISSUE THREAD

**Issue by GordonHuangYong** [GONZALEZD/cupertino_listview#9]
![image](https://user-images.githubusercontent.com/20039800/206184122-8c2a7c4c-49a1-4d62-bc52-bb1847fff20b.png)
![image](https://user-images.githubusercontent.com/20039800/206184154-daa682b8-61b6-411a-b966-54c22e178249.png)

**Comment by GONZALEZD** [comment]
Documentation will be updated to reflect a required parameter.
Thank you for notifying me that mistake
